# Generated by Django 3.0.14 on 2021-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
